### ISSUE TITLE
Automatic scroll down in the GUI for protocol output log

### ISSUE THREAD

**Issue by azazellochg** [biocompwebs/scipion#101]
I think it would be nice to have an automatic scroll down to the last line in the GUI tab "Output log" for both run.stdout and run.log. Especially when restarting/changing a protocol several times thus having a rather long log file, it would be handy. And maybe add a tickbox [scroll lock], if considered necessary..

**Comment by delarosatrevin** [comment]
Now when you click on the "Refresh" icon in the output viewer, the scroll goes to the end. The same if you change from one protocol to the other. Some other minor fixes have been done when reloading logs. @azazellochg, please re-open the issue if you find any problem.
