### ISSUE TITLE
xmipp auto-picking (step 2) gives an error on input validation

### ISSUE THREAD

**Issue by azazellochg** [biocompwebs/scipion#102]
After manually picking few particles in "xmipp auto-picking (step 1)" and creating output coordinates, the step 2 protocol gives an error on validation of the input particle set: **Input supervised picking run is not valid.** The error is somewhere [here](https://github.com/biocompwebs/scipion/blob/master/pyworkflow/em/packages/xmipp3/protocol_particle_pick_automatic.py#L141).
It appears irrespectively of the set of the micrographs provided (the same or another).

**Comment by airenzp** [comment]
This validation was to ensure that the input picking run had been trained (used autopick), but the error message was not clear. Now states: Input picking run has not been trained, use Autopick for at least one micrograph.

**Comment by azazellochg** [comment]
Probably I don't understand how Xmipp3 picker works. 
After the changes you made I see in the protocol summary (manual-picking step 1) : Autopick : No. After that of course, the next protocol gives new error message on validation. 
How can I run this "Autopick", so that auto-picking (step 2) protocol will work?

**Comment by delarosatrevin** [comment]
Xmipp3 picking can be done in three stages:
1) manual picking (you can pick several micrographs or more than 15 particles in on micrograph)
Note: you can only use manual and never go for steps 2 and 3
2) supervised (this is done in the same run as 1. This stage starts when you click "Autopick" and you start training the algorithm. Any time you change a micrograph it will propose you particles, then you can add or delete and from this it "learns". After a few more micrographs with the training you should create the output SetOfCoordinates.
3) Completely automatic, using a previous run that have done the training (stage 2). After this it should create another SetOfParticles as output that can be reviewed (added or deleted more particles) again.

**Comment by azazellochg** [comment]
Aaah, I see, my fault I didn't notice Autopick checkbox in the first step - it's not readily visible :) Thank you for a swift explanation!

**Comment by delarosatrevin** [comment]
@azazellochg , find the seven differences.... ;)

![picking_activate_training](https://cloud.githubusercontent.com/assets/8441688/9494055/22201e18-4c04-11e5-8213-7b67d95a2ed2.png)
