### ISSUE TITLE
incorrect coordinates import from eman2 box files

### ISSUE THREAD

**Issue by azazellochg** [biocompwebs/scipion#104]
When importing eman2 coordinates from box files, no changes are applied, e.g. (x,y) in eman2 box file are (x,y) in scipion pos file.
This is incorrect since eman stores the coordinates of left-bottom box corner and not the particle center. One needs to add half-box size to both X and Y to convert from eman2 to scipion.
[the error is in there, i guess](https://github.com/biocompwebs/scipion/blob/master/pyworkflow/em/packages/eman2/dataimport.py)

~~PS. I didn't check the import from json files, but since it's done in a similar manner, I guess it's also wrong.~~

**Comment by delarosatrevin** [comment]
In Eman 2.1 the coordinates are in the center of the box...a big change yes. Maybe we could easily adapt the import to allow both center and left-corner coordinates.
Import from json files is not working right now...but can be easily added in a near future.

**Comment by delarosatrevin** [comment]
Did you import from protocol or from Xmipp GUI???

**Comment by azazellochg** [comment]
I used import coordinates protocol in Scipion.
Also, I'm using EMAN2.1 for half a year and didn't see any changes in box files conventions (neither I saw any announcement from Steve). Where did you get this?..
 I have just picked few particles in e2boxer (EMAN 2.1 CVS 2015/05/10 09:00:03) and for the ones that are on the edge of the micrograph (center of the particle is within the mic, but the left bottom corner is outside) I see in box file clearly negative values indicating that left-bottom corner coordinates are still used.

**Comment by delarosatrevin** [comment]
We have check it in the .json files. Now if you open the Eman boxer and just click Done. The json files have the center of the coordinate. I'm not sure if they still generate the .box files if you click on "Write output". A simple test that I did to double-check now was to pick a single particle with the size almost half of the micrograph...and then it was close to the top-left border...so in the .json file is easy to check if is the top-left corner of the box or the center...and it was the center in my case. I would appreciate any feedback from your side on this.

**Comment by azazellochg** [comment]
You are right, I've checked again:
box file: 1       1       128     128
json file: "boxes": [[65.09786195554463, 65.08147627228456, "manual"]

So, in case of box files we need to add half-box size during import..

**Comment by delarosatrevin** [comment]
@airenzp , check this issue when importing .box files, also do some code cleanup in file:

pyworkflow/em/protocol/protocol_import/coordinates.py

Check the tests related to import coordinates and add new ones if necessary.

**Comment by azazellochg** [comment]
I have just tried to import box files using scipion from fresh version of 1.0 branch, where this bug was fixed. 
However, I get this error message:

 Traceback (most recent call last):
00013:     File "/home/sharov/soft/scipion/pyworkflow/protocol/protocol.py", line 167, in run
00014:       self._run()
00015:     File "/home/sharov/soft/scipion/pyworkflow/protocol/protocol.py", line 211, in _run
00016:       resultFiles = self._runFunc()
00017:     File "/home/sharov/soft/scipion/pyworkflow/protocol/protocol.py", line 207, in _runFunc
00018:       return self._func(*self._args)
00019:     File "/home/sharov/soft/scipion/pyworkflow/em/protocol/protocol_import/coordinates.py", line 103, in createOutputStep
00020:       ci.importCoordinates(coordFile, addCoordinate=addCoordinate)
00021:     File "/home/sharov/soft/scipion/pyworkflow/em/packages/eman2/dataimport.py", line 62, in importCoordinates
00022:       half = size / 2
00023:   TypeError: unsupported operand type(s) for /: 'NoneType' and 'int'
00024:   Protocol failed: unsupported operand type(s) for /: 'NoneType' and 'int'

I guess *size* somehow was not defined..

**Comment by delarosatrevin** [comment]
I couldn't reproduce your error. It seems like a problem parsing the .box file and retrieving the box size.
That is size=None. I tried even with only two column box file and I got wrong coordinates but not this error. 
Could you check your .box files? Can you send me one of them? There are from Eman2.x version?

**Comment by azazellochg** [comment]
You are right, my fault. I have used a different program to generate box files (Gautomatch). Inside I have 6 columns: X, Y, sizeX, sizeY, CC, template_number. I was expecting scipion to read only first three/four columns.

**Comment by delarosatrevin** [comment]
Can you send me a file anyway? I would expect that Scipion will read only
the first 3 columns and ignore the rest.
So I think this should not be an issue if it is a text file.

**Comment by azazellochg** [comment]
here it is. 
[mount35-18.box.txt](https://github.com/biocompwebs/scipion/files/33854/mount35-18.box.txt)

**Comment by delarosatrevin** [comment]
I have tested with this file and it was imported correctly. Maybe another
one of the imported files?
I added a validation if size becomes None to print the 'problematic' file
and skip it. This could
give us a hint about what is happening.

**Comment by azazellochg** [comment]
Found them! There were two empty box files among thousand normal ones. Thanks for the help, @delarosatrevin

**Comment by delarosatrevin** [comment]
Great!, thanks you also. Now the import is more robust to empty .box files
:)
