### ISSUE TITLE
When running eman initial volume, in tests or web, sometimes fails

### ISSUE THREAD

**Issue by airenzp** [biocompwebs/scipion#105]
00012: /mnt/big1/scipion-service/usr/scipion/software/em/eman/Python/bin/python /mnt/big1/scipion-service/usr/scipion/software/em/eman/bin/e2initialmodel.py --input=../representatives.stk iter=8 --tries=10 --sym=d7 --parallel=thread:8 
00013: Models will be 1.000 A/pix 
00014: Exception in thread Thread-1: 
00015: Traceback (most recent call last): 
00016: File "/mnt/big1/scipion-service/usr/scipion/software/em/eman/Python/lib/python2.7/threading.py", line 551, in __bootstrap_inner 
00017: self.run() 
00018: File "/mnt/big1/scipion-service/usr/scipion/software/em/eman/Python/lib/python2.7/threading.py", line 504, in run 
00019: self.__target(*self.__args, **self.__kwargs) 
00020: File "/mnt/big1/scipion-service/usr/scipion/software/em/eman/lib/EMAN2PAR.py", line 571, in run 
00021: proc=subprocess.Popen(["e2parallel.py","localclient","--taskin=%s/%07d"%(self.scratchdir,self.nextid),"--taskout=%s/%07d.out"%(self.scratchdir,self.nextid)]) 
00022: File "/mnt/big1/scipion-service/usr/scipion/software/em/eman/Python/lib/python2.7/subprocess.py", line 679, in __init__ 
00023: errread, errwrite) 
00024: File "/mnt/big1/scipion-service/usr/scipion/software/em/eman/Python/lib/python2.7/subprocess.py", line 1249, in execute child 
00025: raise child_exception 
00026: OSError: [Errno 2] No such file or directory

**Comment by delarosatrevin** [comment]
Check this with @josuegbl when porting and testing Web-tools in Nolan.
