### ISSUE TITLE
scripts/split_stacks.py does not split SerialEM stacks

### ISSUE THREAD

**Issue by azazellochg** [biocompwebs/scipion#106]
I wanted to import mrc stacks (from SerialEM), but apparently the script just copies the original files and not splitting them. The command I ran was:
`scipion run ~/soft/scipion/scripts/split_stacks.py --files "raw/mount*.mrc" --ext mrc`

* Input file: mount1.mrc
* Ouput files: mount1_NNN.mrc are all identical to input file

Maybe I'm doing smth wrong?

**Comment by delarosatrevin** [comment]
.mrc format is quite problematic...in its original definition there is no distinction between 2d stacks and 3D volumes. There is some agreement to set a flag to differentiate but is not followed by all packages. Anyway I have added a suffix ":mrcs" that in this context means to treat always as stack. 
Now it should work with your micrographs stacks.

**Comment by azazellochg** [comment]
Thanks, I hope scipion will adapt/promote the MRC2014 standard ;P
