### ISSUE TITLE
copyItems assumes input "metadatas" are sorted. This may not be the case

### ISSUE THREAD

**Issue by rmarabini** [biocompwebs/scipion#111]
Follows a list with all programs that use copyItems. At least xmipp and relion progrms should be checked. 

pyworkflow/em/data.py:                newItem.copyItems(item, copyDisabled=copyDisabled)
pyworkflow/em/packages/eman2/convert.py:    imgSet.copyItems(partSet,
pyworkflow/em/packages/eman2/protocol_refineasy.py:        newPartSet.copyItems(partSet,
pyworkflow/em/packages/relion/protocol_refine3d.py:            outImgSet.copyItems(imgSet,
pyworkflow/em/packages/xmipp3/protocol_apply_alignment.py:        alignedSet.copyItems(particles,
pyworkflow/em/packages/xmipp3/protocol_preprocess/protocol_process.py:        outputSet.copyItems(inputSet, 
pyworkflow/em/packages/xmipp3/protocol_projection_outliers.py:        outputSet.copyItems(inputSet, 
pyworkflow/em/packages/xmipp3/protocol_projmatch/protocol_projmatch.py:        partSet.copyItems(imgSet,
pyworkflow/em/packages/xmipp3/protocol_screen_classes.py:        outputSet.copyItems(inputSet, 
pyworkflow/em/protocol/protocol_alignment_assign.py:        outputParticles.copyItems(inputParticles,
pyworkflow/em/protocol/protocol_import/dataimport.py:        micSet.copyItems(inputSet, updateItemCallback=self._updateParticle)
pyworkflow/em/protocol/protocol_import/dataimport.py:        partSet.copyItems(inputSet, updateItemCallback=self._updateParticle)

The following line is an example in which the metadata is sorted 

            outImgSet.copyItems(imgSet,
                                updateItemCallback=self._createItemMatrix,
                                itemDataIterator=md.iterRows(outImgsFn, sortByLabel=md.MDL_ITEM_ID))

**Comment by delarosatrevin** [comment]
Check the usage of copyItems and if the order is preserved, sometimes can be useful to add a validation (by id or another identifier) in the updateItemCallback
