### ISSUE TITLE
xmipp tests

### ISSUE THREAD

**Issue by rmarabini** [biocompwebs/scipion#116]
if you run

/home/roberto/Scipion/scipion-code/data/tests/xmipp_programs/tmpLink/xmipp_angular_project_library_01/output_projections.doc

the command lunched is

xmipp_angular_project_library -i input/phantomBacteriorhodopsin.vol -o tmpLink/xmipp_angular_project_library_01/output_projections.stk --sym c6 --sampling_rate 5 --compute_neighbors --experimental_images input/aFewProjections.sel  --angular_distance -1

while it should be

xmipp_angular_project_library -i input/phantomBacteriorhodopsin.vol -o tmpLink/xmipp_angular_project_library_02/output_projections.stk --sym c6 --sampling_rate 5 --compute_neighbors --experimental_images input/aFewProjections.sel  --angular_distance -1

that is:

xmipp_angular_project_library_01

should be 

xmipp_angular_project_library_02

**Comment by delarosatrevin** [comment]
Now the function unittest.TestCase.id(self) is used to retrieve the case number to create the output folder and compare with the gold results.
