### ISSUE TITLE
bshow 1.8.8 does not work

### ISSUE THREAD

**Issue by azazellochg** [biocompwebs/scipion#122]
While trying to use bsoft particle picker, I got an error upon displaying an mrc file:

>
>00027:   bshow Falcon_2012_06_12-14_33_35_0.mrc
>00028:   Error in startup script: floating point value is Not a Number
00029:       while executing
00030:   "$wc.slice.scale set $oz"
00031:       (procedure "loadImage" line 69)
00032:       invoked from within
00033:   "loadImage $filename -1"
00034:       invoked from within
00035:   "if { $file_type == 1 } {
00036:   	set paramdir [file dirname $filename]
00037:   	set modeldir [file dirname $filename]
00038:   	loadImage $filename -1
00039:   } elseif { $file_type =..."
00040:       (file "/home/sharov/soft/scipion/software/em/bsoft/bin/bshow" line 474)
00041:   Traceback (most recent call last):
00042:     File "/home/sharov/soft/scipion/pyworkflow/protocol/protocol.py", line 167, in run
00043:       self._run()
00044:     File "/home/sharov/soft/scipion/pyworkflow/protocol/protocol.py", line 211, in _run
00045:       resultFiles = self._runFunc()
00046:     File "/home/sharov/soft/scipion/pyworkflow/protocol/protocol.py", line 207, in _runFunc
00047:       return self._func(*self._args)
00048:     File "/home/sharov/soft/scipion/pyworkflow/em/packages/bsoft/protocol_particle_pick.py", line 78, in launchParticlePickGUIStep
00049:       self.runJob("bshow", basename(mic.getFileName()))
00050:     File "/home/sharov/soft/scipion/pyworkflow/protocol/protocol.py", line 940, in runJob
00051:       self._stepsExecutor.runJob(self._log, program, arguments, **kwargs)
00052:     File "/home/sharov/soft/scipion/pyworkflow/protocol/executor.py", line 56, in runJob
00053:       env=env, cwd=cwd)
00054:     File "/home/sharov/soft/scipion/pyworkflow/utils/process.py", line 51, in runJob
00055:       return runCommand(command, env, cwd)
00056:     File "/home/sharov/soft/scipion/pyworkflow/utils/process.py", line 65, in runCommand
00057:       check_call(command, shell=True, stdout=sys.stdout, stderr=sys.stderr, env=env, cwd=cwd)
00058:     File "/home/sharov/soft/scipion/software/lib/python2.7/subprocess.py", line 540, in check_call
00059:       raise CalledProcessError(retcode, cmd)
00060:   CalledProcessError: Command 'bshow Falcon_2012_06_12-14_33_35_0.mrc' returned non-zero exit status 1
00061:   FAILED: launchParticlePickGUIStep, step 1
...

I have tried to launch bshow outside scipion workflow and got the same error. However, updating to bsoft 1.9.0 solved the problem

**Comment by delarosatrevin** [comment]
I got the same problem. I have added bsoft-1.9.0 as possible version to install. (**scipion install --help** will show all options). I tested and the micrographs showed up in the picking. If you install it, you will need to edit your ~/.config/scipion/scipion.conf and set BSOFT_HOME=bsoft-1.9.0.

Note anyway that the picking in bsoft right now is not at it full potential, you need to go through each micrograph one by one...and remember to SAVE PARAMETERS for each one (keeping the default name for .star file)
