### ISSUE TITLE
xmipp3 apply 2d mask protocol works only on a single image

### ISSUE THREAD

**Issue by azazellochg** [biocompwebs/scipion#124]
When I apply a 2d mask from a file or a designed mask to a set of particles I get an error:

>00018:   STARTED: maskStep, step 3
00019:     2015-11-17 17:20:14.170785
00020:   xmipp_image_operate -i Runs/003632_XmippProtMaskParticles/tmp/input_particles.xmd --mult Runs/003632_XmippProtMaskParticles/tmp/mask.spi -o Runs/003632_XmippProtMaskParticles/extra/output_images.stk --save_metadata_stack Runs/003632_XmippProtMaskParticles/extra/output_images.xmd --keep_input_columns
**00021:   XMIPP_ERROR 31:  MetaData error.
00022:   Both metadatas operands should be of same size.**
00023:   File: software/em/xmipp/libraries/data/image_operate.cpp line: 430
00024:   For more info use --help
00025:   Input File: Runs/003632_XmippProtMaskParticles/tmp/input_particles.xmd
00026:   Output File: Runs/003632_XmippProtMaskParticles/extra/output_images.stk
00027:   0000/???? sec. ------------------------------------------------------------XMIPP_ERROR 32:  No active object in MetaData.
00028:   getValue: please provide objId other than -1
00029:   File: software/em/xmipp/libraries/data/metadata.cpp line: 209
00030:   Traceback (most recent call last):
00031:     File "/home/sharov/soft/scipion/pyworkflow/protocol/protocol.py", line 167, in run
00032:       self._run()
00033:     File "/home/sharov/soft/scipion/pyworkflow/protocol/protocol.py", line 211, in _run
00034:       resultFiles = self._runFunc()
00035:     File "/home/sharov/soft/scipion/pyworkflow/protocol/protocol.py", line 207, in _runFunc
00036:       return self._func(*self._args)
00037:     File "/home/sharov/soft/scipion/pyworkflow/em/packages/xmipp3/protocol_preprocess/protocol_mask.py", line 119, in maskStep
00038:       self.runJob(self._program, args)
00039:     File "/home/sharov/soft/scipion/pyworkflow/protocol/protocol.py", line 940, in runJob
00040:       self._stepsExecutor.runJob(self._log, program, arguments, **kwargs)
00041:     File "/home/sharov/soft/scipion/pyworkflow/protocol/executor.py", line 56, in runJob
00042:       env=env, cwd=cwd)
00043:     File "/home/sharov/soft/scipion/pyworkflow/utils/process.py", line 51, in runJob
00044:       return runCommand(command, env, cwd)
00045:     File "/home/sharov/soft/scipion/pyworkflow/utils/process.py", line 65, in runCommand
00046:       check_call(command, shell=True, stdout=sys.stdout, stderr=sys.stderr, env=env, cwd=cwd)
00047:     File "/home/sharov/soft/scipion/software/lib/python2.7/subprocess.py", line 540, in check_call
00048:       raise CalledProcessError(retcode, cmd)
00049:   CalledProcessError: Command 'xmipp_image_operate -i Runs/003632_XmippProtMaskParticles/tmp/input_particles.xmd --mult Runs/003632_XmippProtMaskParticles/tmp/mask.spi -o Runs/003632_XmippProtMaskParticles/extra/output_images.stk --save_metadata_stack Runs/003632_XmippProtMaskParticles/extra/output_images.xmd --keep_input_columns' returned non-zero exit status 32
00050:   Protocol failed: Command 'xmipp_image_operate -i Runs/003632_XmippProtMaskParticles/tmp/input_particles.xmd --mult Runs/003632_XmippProtMaskParticles/tmp/mask.spi -o Runs/003632_XmippProtMaskParticles/extra/output_images.stk --save_metadata_stack Runs/003632_XmippProtMaskParticles/extra/output_images.xmd --keep_input_columns' returned non-zero exit status 32
00051:   FAILED: maskStep, step 3

Both input particles and a mask have same dimensions / pixel size. However, if I apply a mask to a single particle (a subset with 1 element) it works.

**Comment by delarosatrevin** [comment]
Thanks one more time for finding this bug. Fixed, it was a problem in the xmipp program (xmipp_image_operate) when using metadatas and some mask extensions.  Now after update/recompile should work.

I also added a validation that dimensions of input images/volumes and the mask should be the same.
