### ISSUE TITLE
The conversion tests in Bsoft are not working

### ISSUE THREAD

**Issue by delarosatrevin** [biocompwebs/scipion#126]
If you run the test:
scipion test tests.em.data.test_convert_bsoft

you will see several test cases failing. 
(Either with bsoft version 1.8.8 or new 1.9.0, that can be installed)

**Comment by rmarabini** [comment]
They have never work.  I just create for laura who decided that bsoft was not the way to go. If nobody is interesting in implementing bsoft the best you can do is delete the test

     Roberto
