### ISSUE TITLE
Option --boxBorder is not a valid option in gEMPicker (0.9 or 1.1)

### ISSUE THREAD

**Issue by delarosatrevin** [biocompwebs/scipion#132]
This option is not among the available ones.

@azazellochg, could you check this? It is somehow related to #51

**Comment by azazellochg** [comment]
You are right, it was added only in a "new" 1.1 version.

**Comment by delarosatrevin** [comment]
Fixed, now @azazellochg have sent me this "new" 1.1 version...this one is available in Scipion.

**Comment by hvthaibk** [comment]
Finally, the source code of gEMpicker is now available on github. Please let me know if you have any compilation problem in Ubuntu-based platform. 
 - prepare 3rdParty libs: ./install.sh
 - make static executables: ./makeStatic.sh

https://github.com/hvthaibk/ccrunch

**Comment by delarosatrevin** [comment]
Hi Thai, good to hear that the gEMpicker source code is available.
