### ISSUE TITLE
Relion .star file resulting from 3D refinement allows to apply geo/wrap

### ISSUE THREAD

**Issue by delarosatrevin** [biocompwebs/scipion#135]
This .star file contains information of 3D angular assignment but should not allow to apply geo (the same as in Xmipp), maybe you can compare with a .xmd file resulting from projection matching.

This issue is somehow related to #92

**Comment by airenzp** [comment]
If rot ant tilt are present is probably a projection, so no geo applied. Relion defines these labels in 2D but they are set to cero
