### ISSUE TITLE
The "Selection from here/ remove disabled" is not working in .star files

### ISSUE THREAD

**Issue by delarosatrevin** [biocompwebs/scipion#136]
If you "Analyze Results" in relion 2D/3D and open optimiser file and from there open data file...
then select from and remove disable does not work...I noticed that there is not enable column (xmipp default one, it is present rlnEnabled) and I'm not sure if this can be related with the problem.

**Comment by pconesa** [comment]
Bugfix: viewer disable all images of metadata files from relion when disabling only one. (Fixed: new column enable" is added with 0 values as default. We are assuming -1 is false, else, true, So 0 or 1 are both true.)
