### ISSUE TITLE
Queue parameters should not be propagated from previous selection when changing the queue 

### ISSUE THREAD

**Issue by azazellochg** [biocompwebs/scipion#138]
This is a bit difficult to explain. Here are my queue params from config/hosts.conf:

        #SBATCH -p %_(JOB_QUEUE)s
        #SBATCH -A %_(JOB_ACCOUNT)s
        #SBATCH --time=%_(JOB_TIME)s-00 --ntasks=%_(JOB_NODES)d --cpus-per-task=%_(JOB_THREADS)d %_(JOB_PARAMS)s
...

>
QUEUES = {
        "grant": [["JOB_MEMORY", "64000", "Memory (MB)", "Select amount of memory (in megabytes) for this job"],
                   ["JOB_TIME", "4", "Time (days)", "Select the time expected (in days) for this job"],
                   ["JOB_ACCOUNT", "g2014a90", "Account", "Select the account name for the queue"],
                   ["JOB_PARAMS", "", "Other parameters", "Additional parameters for SBATCH command"]
                  ],
        "igbmc2015": [["JOB_MEMORY", "128000", "Memory (MB)", "Select amount of memory (in megabytes) for this job"],
                       ["JOB_TIME", "14", "Time (days)", "Select the time expected (in days) for this job"],
                       ["JOB_ACCOUNT", "qosigbmc2015", "Account", "Select the account name for the queue"],
                       ["JOB_PARAMS", "", "Other parameters", "Additional parameters for SBATCH command"]
                      ],
        "publicgpu": [["JOB_TIME", "1", "Time (days)", "Select the time expected (in days) for this job"],
                       ["JOB_ACCOUNT", "igbmc", "Account", "Select the account name for the queue"],
                       ["JOB_PARAMS", "--gres=gpu:1 --ntasks-per-socket=8 --ntasks=8", "Other parameters", "Default parameters for jobs running on GPU"]
                      ]
        }

When I start a new protocol and select to submit it on the queue, I get a list of parameters (time,memory,account) that are auto-filled when I switch to a different queue name (see the pics) - i.e. everything works fine.

![new_protocol-queue1](https://cloud.githubusercontent.com/assets/6952870/11420171/b568c52e-942c-11e5-888b-8052f29b6230.png)
![new_protocol-queue2](https://cloud.githubusercontent.com/assets/6952870/11420173/b8ecf878-942c-11e5-9175-14ea7233c247.png)
![new_protocol-queue3](https://cloud.githubusercontent.com/assets/6952870/11420176/bbf70842-942c-11e5-92ef-33ae34879179.png)

However, if I copy or edit an executed protocol (mode: restart, queue was **grant**) and try to select a different queue name - parameters do not automatically change, they stay as they were for the queue on which the protocol was executed - **grant** (see the next pics). In this case I have to edit them manually. The only exception is JOB_PARAMS that seems to change.

![edit_protocol-queue1](https://cloud.githubusercontent.com/assets/6952870/11420183/cd348800-942c-11e5-9cdf-91d08f1fa8ce.png)
![edit_protocol-queue2](https://cloud.githubusercontent.com/assets/6952870/11420185/d022b820-942c-11e5-982d-b6ab2360c32f.png)
![edit_protocol-queue3](https://cloud.githubusercontent.com/assets/6952870/11420187/d330f216-942c-11e5-9e26-ef36c9965346.png)

**Comment by delarosatrevin** [comment]
This was the desired behavior. I guess if you change from one queue to another, not always the best option is to propagate the selected parameters. What I think is behaving as unexpected is that are propagated for the first case you mention. Anyway, we can discuss more about this topic.

**Comment by azazellochg** [comment]
I agree that keeping all old parameters (queue name, time etc) upon copying or editing a protocol is useful (so that user don't need to select all of them once again). But I do not see how this helps if user deliberately changes the queue (whether during creation/editing/copying the protocol)...  At least in my case I have 3 different queues with completely different parameters and they are not interchangeable.

The only case, I guess this might be helpful for, is if there are several similar queues with similar parameters, and e.g., user resubmitting the job to a less busy queue.

**Comment by delarosatrevin** [comment]
Ok, I got you point now. I thought before that you wish to propagate the parameters from one queue to another...but is just the opposite. So we both agreed that the safe way is to not copy parameters from one queue to another. I will check this.

**Comment by delarosatrevin** [comment]
Closed by commit 6dfafb747b9, now it should behave as expected. 
@azazellochg , please let me know after you can test it.

**Comment by azazellochg** [comment]
I have checked, it works fine now! :+1:
