### ISSUE TITLE
WEB: Error in the protocol movie alignment window

### ISSUE THREAD

**Issue by pconesa** [biocompwebs/scipion#144]
when you load the movie alignment protocol window and inspect the page in the browser this error appears:

Uncaught Error: Syntax error, unrecognized expression: tr#DosefGPU/Croscorrelation_parameters

Also the section of parameters exclusive to gpu alignment method is shown and it shouldn't: related?

**Comment by delarosatrevin** [comment]
Maybe the / in the Section name is not liked by #Something in web??? Or any internal tag?

**Comment by pconesa** [comment]
That was it!, fixed now.
