### ISSUE TITLE
base classes are displayed in Search protocol dialog

### ISSUE THREAD

**Issue by azazellochg** [biocompwebs/scipion#147]
I find it a bit confusing, since in "Search protocol" dialog you can find all the "base" protocols and classes without any input params (in GUI) etc, like scipion-batch protocol, scipion-ProtMicrographs and many others

**Comment by delarosatrevin** [comment]
Fixed in commit 01e3fbc1227a304. Now the "Search Protocol" dialog check that the protocol not "isBase()".
It is assumed that if a protocol does not define _label, or it is None, is a base class.  Let me know if you still find some base protocol in the wrong place.

**Comment by azazellochg** [comment]
@delarosatrevin Thanks for a fix! Maybe it is also worth to sort protocols by name in this list? Might be easier to orient there..

**Comment by delarosatrevin** [comment]
Totally agree. Done in commit f0716d7. Thanks for the feedback.
