### ISSUE TITLE
Install and test scipion on crunchy

### ISSUE THREAD

**Issue by ldelcano** [biocompwebs/scipion#17]
Install it on folder /gpfs/fs1/apps/scipion/ with user xmipp.
First we got an error cause git was old. Jesus installed a new git (2.4) but to use it you need to source . /gpfs/fs1/home/bashrc on your env.
Then we got an error trying to install scipy and opencv so we installed it without those modules.
Then we run some tests and found that Eman 2.1 does not work cause it has been precompiled with a libc library wich is not the one on crunchy system. According to Jesus this cannot be changed without reinstalling crunchy.
Relion movie alignment does not work cause it needs opencv.
Resmap cannot be installed either cause it depends on scipy.
After updating scipion when run scipion install it failed installing pcre-8.36. IT gives following error:

make1: Entering directory `/gpfs/fs1/apps/scipion/software/tmp/pcre-8.36'
CXXLD libpcrecpp.la
/usr/lib64/gcc/x86_64-suse-linux/4.1.2/../../../../x86_64-suse-linux/bin/ld: .libs/libpcrecpp_la-pcrecpp.o: relocation R_X86_64_PC32 against `std::basic_string<char, std::char
_traits<char>, std::allocator<char> >::~basic_string()@@GLIBCXX_3.4' can not be used when making a shared object; recompile with -fPIC
/usr/lib64/gcc/x86_64-suse-linux/4.1.2/../../../../x86_64-suse-linux/bin/ld: final link failed: Bad value
collect2: ld returned 1 exit status
make1: *** [libpcrecpp.la] Error 1

The problem was that pcre lib is compiled with flag fPIC while libpcrecpp_la-pcrecpp.o (which is linked byt it) is not. Jordi fixed it.

**Comment by delarosatrevin** [comment]
@ldelcano I think we can close this issue, knowing the limitations on crunchy and maybe also in similar old systems.
