### ISSUE TITLE
Compute PSD before and after any alignment and at protocol level

### ISSUE THREAD

**Issue by rmarabini** [biocompwebs/scipion#26]
After discussing with Vahid I think the  PSD computed by the movie alignment protocol is divided in two halves showing the PSD before and after running optical flow. May be we should modify it so it shows the psd before dosegpu is used (if selected in the protocol)

**Comment by delarosatrevin** [comment]
@rmarabini , you were talking with @vabrishami ??? Just to re-call the tagging system.
Anyway, if the dosefgpu is not used? Then the two PSD halves when are computed?

**Comment by rmarabini** [comment]
inside optical_flow program (it would have been cleaner to do it in the protocol)

**Comment by delarosatrevin** [comment]
I think this will not be ready for v1.0, so I will change the milestone.

**Comment by delarosatrevin** [comment]
@vabrishami , please check if you have finished this and close the issue.
