### ISSUE TITLE
Subset output is duplicated in the db

### ISSUE THREAD

**Issue by delarosatrevin** [biocompwebs/scipion#35]
When creating a subset (let say of averages out of some classes) and in a further
step I try to select recently created averages, the object appears duplicated....

@ldelcano , could you help @airenzp  with this issue so she can go back to web as soon as possible?

**Comment by ldelcano** [comment]
https://github.com/delarosatrevin, we cannot reproduce it, could you tell us a bit more on how you got the error?
We created a set of 2 averages from a SetOfClasses (ML2D output) and used it as input on a FilterParticles protocol. We could see the SetOfAverages object just once (when choosing it and also after running the filter).

**Comment by ldelcano** [comment]
run.db of Subset run only contains one entry while in project.sqlite it appears duplicated (same ids but twice).

**Comment by delarosatrevin** [comment]
This issue has been fixed in commit cff47dbc8858a79594b29a32709bfd908dbdf080.
The problem was due to parallel execution of project database update when executing protocols from Java.
