### ISSUE TITLE
Time of finished protocols doesn't stop

### ISSUE THREAD

**Issue by delarosatrevin** [biocompwebs/scipion#36]
After finished, the time of each protocol continues counting....I think @ldelcano fixed a related problem some time ago.

**Comment by ldelcano** [comment]
@delarosatrevin could you tell me in which protocol did this happen?
This happened on CL2DAlign in the past cause there was a hidden error even though protocol seemed to finish ok.

**Comment by delarosatrevin** [comment]
I found it in ctffind4 and others...but I can't remember exactly

**Comment by delarosatrevin** [comment]
Seems to be fixed...let's close it and re-open if necessary.
