### ISSUE TITLE
scipion install does not install properlly dosefgpu_driftcorr 

### ISSUE THREAD

**Issue by rmarabini** [biocompwebs/scipion#44]
after instalation of motion_cor the program  dosefgpu_driftcorr  is not in the path
therefore movie_alignment protocol will fail ;-)

**Comment by delarosatrevin** [comment]
@jordibc , check if what @rmarabini  reported is really happening. 
Also @vabrishami wrote to Yifan about the program name and it suggested to use MotionCorr, so please check that we are using this name (or maybe changing lower/upper to follow ours convetions) consistently.

**Comment by jordibc** [comment]
@rmarabini could you check if it works now? or give me a full example of how to run the movie_alignment protocol? (I couldn't find any in the tests). Thanks

**Comment by rmarabini** [comment]
@jordibc I cannot check if it works now :-(. Follows an example

1)  install scipion from scratch  including motioncorr package,
2) import one movie
3) execute align movies selecting dosfegpu option
4)  you will get an error message: dosefgpu_driftcorr not found

**Comment by delarosatrevin** [comment]
@rmarabini, can you check now to close this issue?

**Comment by rmarabini** [comment]
seems to be working now
