### ISSUE TITLE
add gEMpicker to our installer

### ISSUE THREAD

**Issue by jordibc** [biocompwebs/scipion#51]
and show @tranquilinho how to do it :)

**Comment by jordibc** [comment]
To show @tranquilinho how to do it, we used chimera instead.

Actually, I don't think we can download gEMpicker as an external package, because it may break their license, http://gem.loria.fr/license.php , specifically point 4.a

**Comment by delarosatrevin** [comment]
I think I need to check with them....the have a free license for
non-comercial usage.
I can comment that you have finished the first version of the protocol and
we want
to make available for download.

**Comment by cossorzano** [comment]
Maybe we coul contact them and let them decide if they allow us to 
distribute gEMpicker.

**Comment by delarosatrevin** [comment]
@azazellochg , could you please check about the license to download gEMPicker mentioned in this thread?
Remeber to contact Thai or any other person involved.

**Comment by azazellochg** [comment]
@delarosatrevin , I've got a definitive answer: we can distribute binary versions.

**Comment by delarosatrevin** [comment]
Thanks, I have checked the version of those binaries and it is 0.9.

I was checking the binaries that I have from my visit to Strasbourg last year
and I have version 1.1.

Which one should I use? I guess the more recent one should have 
some improvements/bugfixes over the other.

**Comment by azazellochg** [comment]
I see. I'll ask Thai to compile the latest binary with all new options and get back to you.
