### ISSUE TITLE
rediret sdterr in protocols

### ISSUE THREAD

**Issue by rmarabini** [biocompwebs/scipion#52]
std::cerr  commands in C code appears in run.stdout instead run.stderr in protocols

At least this hapends with program

gnedIntermediate.xmd --sampling 1.340000 --cropULCorner -1 -1  --cropDRCorner -1 -1 --frameRange 2 24 --max_shift 16 --oavg Falcon_2015_05_21-15_06_09_0_aligned.mrc --oaligned movie_000001_kk.mrcs 

out put:
Frame 2 to Frame 3 -> (0.967423,-0.0141962)

**Comment by rmarabini** [comment]
observado en master: commit ab638f25a9b9d6f2ca867d488e00985eb5c42439

**Comment by delarosatrevin** [comment]
@rmarabini this behaviour was explicitly requested by @cossorzano to track where the error happens in the std::out output tab, I'm not sure if @jordibc let a flag to define this. We should agree on the final setup and close this issue.

**Comment by rmarabini** [comment]
We have a tab called stderr in the protocol that is empty while the sys.stderr is redirected to the tab called stdout. Something is not consistent here.

**Comment by delarosatrevin** [comment]
It is true that maybe we should hide the stderr tab if not being used.

**Comment by delarosatrevin** [comment]
Now the stderr tab is not show. I also changed to avoid going to the end of the Log each time an automatic refresh is done.
