### ISSUE TITLE
Eman conflict

### ISSUE THREAD

**Issue by rmarabini** [biocompwebs/scipion#54]
If you have eman installed in your computer (outside scipion) at configure so:
For example as:

export EMAN2DIR=/home/roberto/Eman/EMAN2
export PATH=${EMAN2DIR}/bin:${EMAN2DIR}/extlib/bin:$PATH
export PYTHONPATH=${EMAN2DIR}/lib:${EMAN2DIR}/bin:${PYTHONPATH}
alias sparx=sx.py

then when starting scipion you get the mesage

oberto@tumbao:~/Scipion/scipion-code[v1.0]> scipion 
>>>>> python  /home/roberto/Scipion/scipion-code/pyworkflow/apps/pw_manager.py 
>>> Error loading module: 'eman2'
>>> Exception:  /home/roberto/Eman/EMAN2/lib/../extlib/lib/libboost_python.so.1.52.0: undefined symbol: PyUnicodeUCS4_FromEncodedObject
Traceback (most recent call last):
  File "/home/roberto/Scipion/scipion-code/pyworkflow/utils/reflection.py", line 49, in getModules
    m = __import__(f)
  File "/home/roberto/Eman/EMAN2/bin/eman2.py", line 51, in <module>
    from EMAN2 import *
  File "/home/roberto/Eman/EMAN2/lib/EMAN2.py", line 44, in <module>
    from EMAN2_cppwrap import *
  File "/home/roberto/Eman/EMAN2/lib/EMAN2_cppwrap.py", line 33, in <module>
    from libpyAligner2 import *
ImportError: /home/roberto/Eman/EMAN2/lib/../extlib/lib/libboost_python.so.1.52.0: undefined symbol: PyUnicodeUCS4_FromEncodedObject

**Comment by delarosatrevin** [comment]
The pyworkflow/em/packages path is put at the beginning when discovering the modules. That fix this problem.
