### ISSUE TITLE
Update SCIPION_URL / download issues

### ISSUE THREAD

**Issue by tranquilinho** [biocompwebs/scipion#57]
Currently it points to scipionwiki (the old server), but it should point to the actual server (scipion)

In addition to changing the default value in scipion.conf (via template), it is required to integrate the simple download path (/files/scipion) into the web service at scipion

Probably this will help with the "random" download issues

**Comment by delarosatrevin** [comment]
Did you already solved this, @tranquilinho ??

**Comment by tranquilinho** [comment]
Working on it :-)

**Comment by tranquilinho** [comment]
Before clossing this issue, notify scipion users so they also update the URL in their local scipion.conf files

**Comment by tranquilinho** [comment]
SCIPION_URL updated in template. 

Updating also the upload script

**Comment by tranquilinho** [comment]
Upload script updated.

Pending: test the uploads of test data

**Comment by delarosatrevin** [comment]
I think uploads are working again
