### ISSUE TITLE
import does not behave properlly if micrographs are in a stack 

### ISSUE THREAD

**Issue by rmarabini** [biocompwebs/scipion#61]

**Comment by delarosatrevin** [comment]
Right now it is not possible to import micrographs from a stack, what we can do right now is put a validation to avoid using stacks for micrographs.

**Comment by rmarabini** [comment]
May be in the error message we may include the following python script to convert from stacks to plain micrographs.
--------------------------------------------------------------------------------------------------
# this script should be executed with the following command line
# scipion run python ./scriptName.py
import glob
import os
#The following two lines may need modification
PATTERN='*.mrcs'           # file names no be processed
NUMBEROFELEMENTSINSTACK=34 # number of elements in each stack
#
isMRC = False

for fileN in glob.glob(PATTERN):
   fileName, fileExtension = os.path.splitext(fileN)
   if fileExtension=='mrc':
       isMRC=True
   for n in range (1,NUMBEROFELEMENTSINSTACK+1):
       if isMRC:
          inFileName = "$s:mrcs"%fileN
       else:
          inFileName = fileN 
       command = 'xmipp_image_convert -i %d@%s -o %s_%03d.mrc -t img'%(n,inFileName,fileName,n)
       os.system(command)
       print "Executing: " + command
