### ISSUE TITLE
relion classify angular distribution

### ISSUE THREAD

**Issue by rmarabini** [biocompwebs/scipion#75]
At least in relion classify the 2D angular distribution graph is wrong (the one made by relion is OK therefore input angles are right). I have not check the chimera output.

     Roberto

**Comment by josuegbl** [comment]
At least in betagal (d2 symm) tutorial seems  like the same information between 2D angular dist plot and the 3D build chimera from Relion....maybe wrong for higher symmetries?

**Comment by rmarabini** [comment]
Ok, I close it
