### ISSUE TITLE
visualize 3D central section

### ISSUE THREAD

**Issue by rmarabini** [biocompwebs/scipion#91]
This has been noted in relion classify 3D but I guess is general. The central section of the 3D map shown by default is not the central section but the previous one. That is, for a 4x4x4 volume the central section (for xmipp) is 2. the visualization shows the second slice but starts counting in 1 (rather than 0 as xmipp does) therefore is not showing the central section but the previous one.

**Comment by delarosatrevin** [comment]
Maybe we should check with @joton this issue in the readPreview function.

**Comment by delarosatrevin** [comment]
It is a showj problem when displaying the central slice of a volume. 
For comparison, in the browser (tkinter) is is displayed correctly (ie. for a 64x64 pixels volume the slice 32 is show)

**Comment by pconesa** [comment]
I might be doing something wrong but after some time looking at these in my test data (RelionClassify3D, final output) the slice displayed is always the number 51 out of 100, which is equivalent to the 2nd slice counting from 0 (xmipp behavior). This behavior has been observed in both, the java viewer (ShowJ) and the web interface...and for .mrc files and .vol files.

Am I missing anything? @rmarabini , @delarosatrevin, @airenzp  ....he,he....probably yes!.

**Comment by delarosatrevin** [comment]
I think you are right @pconesa , I was checking Xmipp center convention here: http://xmipp.cnb.csic.es/twiki/bin/view/Xmipp/Conventions and I think it is ok, let's check with @rmarabini

**Comment by rmarabini** [comment]
closed
