### ISSUE TITLE
Defocus values in CTFModel and Particles are not the "same"

### ISSUE THREAD

**Issue by josuegbl** [biocompwebs/scipion#94]
- There are incoherence in the values after the comma e.g: 10000.6699 vs 10000.6996 if you show the defocus (U o V) value of the particles and its CTFModels.
In the ctfs.sqlite this values are stored with 2 values after the comma, but in particles.sqlite is store with only one. Besides, The showj shows always this values with 4 values.like the example above.

**Comment by delarosatrevin** [comment]
Check if this still persist and if not close the issue.
